// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//  Default [FirebaseOptions] for use with your Firebase apps.

//  Example:
//  ```dart
//  import 'firebase_options.dart';
//  ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
//  ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGGGhlzqmwcDmaRAkmnmdeo8U7EDspKs',
    appId: '1:440847483632:web:87d5ec733b4a9f069c7835',
    messagingSenderId: '440847483632',
    projectId: 'todoappauth-c9622',
    authDomain: 'todoappauth-c9622.firebaseapp.com',
    storageBucket: 'todoappauth-c9622.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlm3A9pqYw5VcivF6vgfh90QBwsLHp5NE',
    appId: '1:440847483632:android:7f32cc35c69b31d39c7835',
    messagingSenderId: '440847483632',
    projectId: 'todoappauth-c9622',
    storageBucket: 'todoappauth-c9622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYLnkzJgQtz2VvXIQbRwO3d-W9tPMOsng',
    appId: '1:440847483632:ios:85fa00b52e3438f49c7835',
    messagingSenderId: '440847483632',
    projectId: 'todoappauth-c9622',
    storageBucket: 'todoappauth-c9622.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
